[package]
name = "cansat"
version = "0.1.0"
authors = ["Sycrosity <72102935+Sycrosity@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32-hal = { version = "0.17.0", features = ["embassy", "embassy-executor-thread", "async", "embassy-time-timg0", "embassy-time"] }
esp-backtrace = { version = "0.9.0", features = ["esp32", "panic-handler", "exception-handler", "print-uart"] }
esp-println = { version = "0.8.0", features = ["esp32","log"] }
log = { version = "0.4.18" }
esp-alloc = { version = "0.3.0" }

# esp-wifi  = { version = "0.1.1", features = ["esp32", "wifi"] }
# smoltcp = { version = "0.10.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }

embedded-svc = { version = "0.26.4", default-features = false, features = [] }
embedded-io = "0.6.1"
heapless = { version = "0.8.0", default-features = false }

embedded-hal-async = "=1.0.0-rc.2"

embedded-graphics = { version = "0.8.1" }
ssd1306 = { version = "0.8.4" }

embassy-executor = { version = "0.4.0", features = ["nightly"]}
embassy-time = "0.2.0"
